### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by mikedotexe** [fastnear/fastnear-api-server-rs#13]
listen bro, all i'm tryna do is get a simple route to return bro

<img width="1037" alt="Screenshot 2024-10-02 at 3 57 39 PM" src="https://github.com/user-attachments/assets/dc63014a-612b-4512-92d2-68a49d04026c">

using the `./run.sh` script, I'm seeing warnings but warnings are okay at this point bro, we're chill bro

![Screenshot 2024-10-02 at 3 58 32 PM](https://github.com/user-attachments/assets/a070409e-36c9-4122-8680-1eb2140fb9b3)

…but what's not chill (bro) is the fact that it's not returning anything. it's not being a bro. but it will on another v1 route that looks identical

![Screenshot 2024-10-02 at 4 01 41 PM](https://github.com/user-attachments/assets/aec684b6-45cd-47e5-83ac-f00f546aa36f)

---

Starting to wonder wild and crazy things. Like is it returning "too fast" where the other ones have to do a db connection? I've tried quite a few things.

cargo clean
remove lockfile
rimraf target
rustup update and try again

bro.

**Comment by mikedotexe** [comment]
here's my fork and a temporary branch for quick reproduction

https://github.com/mikedotexe/fastnear-api-server-rs/blob/542165185ca01743ae349be2779c45d387df5cb2/src/api.rs#L268C13-L286

**Comment by evgenykuzyakov** [comment]
You need to link a new service here: https://github.com/mikedotexe/fastnear-api-server-rs/blob/542165185ca01743ae349be2779c45d387df5cb2/src/main.rs#L66-L73

**Comment by mikedotexe** [comment]
🤦🏼
