### ISSUE TITLE
When will testnet be supported？

### ISSUE THREAD

**Issue by AmazingBeerBelly** [fastnear/fastnear-api-server-rs#2]

**Comment by evgenykuzyakov** [comment]
We're working on a testnet setup, but it will be a while for a full sync

**Comment by AmazingBeerBelly** [comment]
Hello, any update?

**Comment by evgenykuzyakov** [comment]
We've started indexing of testnet. You can monitor: https://test.api.fastnear.com/status
It does miss genesis data though, but shouldn't be such a huge deal

**Comment by evgenykuzyakov** [comment]
It's supported now
