### ISSUE TITLE
Some accounts have empty-string token balances

### ISSUE THREAD

**Issue by Sliman4** [fastnear/fastnear-api-server-rs#8]
For example, in https://api.fastnear.com/v1/ft/sshilly.tkn.near/top `v2.ref-finance.near` and `coldpant65.near` have `""` balance of $sshilly.

These accounts have no problems with (most) other tokens, and other tokens have no problem with (most) accounts, but sometimes it's empty string

**Comment by evgenykuzyakov** [comment]
Seems like it was fixed
